#!/bin/bash
###############################################################################
# 管理后台安全配置脚本
# 功能：为 admin.html 添加 HTTP 基本认证和 IP 白名单保护
###############################################################################

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}管理后台安全配置向导${NC}"
echo -e "${BLUE}================================${NC}"
echo ""

# 检查是否以 root 运行
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}请使用 sudo 运行此脚本${NC}"
    exit 1
fi

# 收集配置信息
echo -e "${BLUE}配置参数${NC}"
echo ""

# 端口配置
read -p "Nginx 监听端口 [8080]: " NGINX_PORT
NGINX_PORT=${NGINX_PORT:-8080}
echo -e "${GREEN}✓ 将使用端口: ${NGINX_PORT}${NC}"
echo ""

# 检查 Nginx 是否已安装
if ! command -v nginx &> /dev/null; then
    echo -e "${RED}未检测到 Nginx，请先安装 Nginx${NC}"
    exit 1
fi

# 查找 Nginx 配置文件
NGINX_CONF="/etc/nginx/sites-available/im-service"
if [ ! -f "$NGINX_CONF" ]; then
    echo -e "${YELLOW}未找到 im-service 配置文件${NC}"
    read -p "请输入 Nginx 配置文件路径: " NGINX_CONF
    if [ ! -f "$NGINX_CONF" ]; then
        echo -e "${RED}配置文件不存在${NC}"
        exit 1
    fi
fi

echo -e "${GREEN}找到配置文件: ${NGINX_CONF}${NC}"
echo ""

# 安装 apache2-utils
echo -e "${BLUE}[1/4] 安装密码工具...${NC}"
if ! command -v htpasswd &> /dev/null; then
    apt install -y apache2-utils
fi
echo -e "${GREEN}✓ 工具已安装${NC}"
echo ""

# 创建密码
echo -e "${BLUE}[2/4] 设置管理员密码${NC}"
read -p "管理员用户名 [admin]: " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-admin}

PASSWD_FILE="/etc/nginx/.htpasswd"
htpasswd -c $PASSWD_FILE $ADMIN_USER
echo -e "${GREEN}✓ 密码已设置${NC}"
echo ""

# 获取 IP 地址（可选）
echo -e "${BLUE}[3/4] 配置访问限制${NC}"
echo ""
echo -e "${YELLOW}是否启用 IP 白名单？${NC}"
echo -e "  ${GREEN}[推荐]${NC} 仅使用密码保护（适合动态 IP）"
echo -e "  如果您的 IP 固定，可以额外添加 IP 白名单提高安全性"
echo ""
read -p "启用 IP 白名单？(y/n) [n]: " USE_WHITELIST
USE_WHITELIST=${USE_WHITELIST:-n}

ALLOWED_IPS=""
if [ "$USE_WHITELIST" == "y" ]; then
    echo ""
    echo -e "当前服务器 IP: ${BLUE}$(curl -s ifconfig.me)${NC}"
    echo -e "您的当前 IP: ${YELLOW}$(who am i --ips 2>/dev/null | awk '{print $NF}')${NC}"
    echo ""
    echo "请输入允许访问的 IP 地址（每行一个，输入空行结束）："
    while true; do
        read -p "IP 或 IP 段: " IP
        if [ -z "$IP" ]; then
            break
        fi
        ALLOWED_IPS="${ALLOWED_IPS}    allow ${IP};\n"
    done
else
    echo -e "${GREEN}✓ 仅使用 HTTP 基本认证（密码保护）${NC}"
fi

# 备份原配置
cp $NGINX_CONF ${NGINX_CONF}.backup.$(date +%Y%m%d_%H%M%S)
echo -e "${GREEN}✓ 已备份原配置${NC}"

# 添加保护配置
echo -e "${BLUE}[4/4] 更新 Nginx 配置...${NC}"

# 生成完整的 Nginx 配置
cat > $NGINX_CONF <<EOF
# IM Service Nginx Configuration
# Generated by secure-admin.sh

upstream im_backend {
    server 127.0.0.1:3001;
    keepalive 64;
}

server {
    listen ${NGINX_PORT};
    server_name _;

    access_log /var/log/nginx/im-service-access.log;
    error_log /var/log/nginx/im-service-error.log;

    # 保护管理后台
    location /admin.html {
EOF

# 添加 IP 白名单（如果启用）
if [ "$USE_WHITELIST" == "y" ]; then
    echo "$ALLOWED_IPS" >> $NGINX_CONF
    echo "        deny all;" >> $NGINX_CONF
    echo "" >> $NGINX_CONF
fi

# 继续添加认证和静态文件配置
cat >> $NGINX_CONF <<EOF
        auth_basic "IM Service Admin Panel";
        auth_basic_user_file ${PASSWD_FILE};

        root /opt/im-service;
        try_files \$uri \$uri/ =404;
    }

    # 保护测试页面
    location ~* ^/(test\.html|ws-client-test\.html)\$ {
EOF

# 测试页面也添加白名单（如果启用）
if [ "$USE_WHITELIST" == "y" ]; then
    echo "$ALLOWED_IPS" >> $NGINX_CONF
    echo "        deny all;" >> $NGINX_CONF
    echo "" >> $NGINX_CONF
fi

cat >> $NGINX_CONF <<EOF
        auth_basic "IM Service Test Pages";
        auth_basic_user_file ${PASSWD_FILE};

        root /opt/im-service;
        try_files \$uri \$uri/ =404;
    }

    # HTTP API
    location /api/ {
        proxy_pass http://im_backend;
        proxy_http_version 1.1;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_cache_bypass \$http_upgrade;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # WebSocket
    location / {
        proxy_pass http://im_backend;
        proxy_http_version 1.1;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

    # 健康检查
    location /health {
        proxy_pass http://im_backend/health;
        access_log off;
    }
}
EOF

# 测试配置
echo ""
echo -e "${BLUE}测试 Nginx 配置...${NC}"
if nginx -t; then
    echo -e "${GREEN}✓ 配置测试通过${NC}"

    # 重启 Nginx
    echo -e "${BLUE}重启 Nginx...${NC}"
    systemctl reload nginx
    echo -e "${GREEN}✓ Nginx 已重启${NC}"
else
    echo -e "${RED}✗ 配置测试失败${NC}"
    echo -e "${YELLOW}正在恢复备份...${NC}"
    cp ${NGINX_CONF}.backup.* $NGINX_CONF
    systemctl reload nginx
    echo -e "${YELLOW}已恢复到原配置${NC}"
    exit 1
fi

# 完成
# 获取服务器 IP
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || echo "your-server-ip")

echo ""
echo -e "${GREEN}================================${NC}"
echo -e "${GREEN}安全配置完成！${NC}"
echo -e "${GREEN}================================${NC}"
echo ""
echo -e "${BLUE}配置信息：${NC}"
echo -e "  端口: ${YELLOW}${NGINX_PORT}${NC}"
echo -e "  服务器 IP: ${YELLOW}${SERVER_IP}${NC}"
echo ""
echo -e "${BLUE}访问地址：${NC}"
echo -e "  管理后台: ${YELLOW}http://${SERVER_IP}:${NGINX_PORT}/admin.html${NC}"
echo -e "  API 接口: ${YELLOW}http://${SERVER_IP}:${NGINX_PORT}/api/${NC}"
echo -e "  健康检查: ${YELLOW}http://${SERVER_IP}:${NGINX_PORT}/health${NC}"
echo ""
echo -e "${BLUE}登录凭证：${NC}"
echo -e "  用户名: ${YELLOW}${ADMIN_USER}${NC}"
echo -e "  密码: ${YELLOW}(您刚才设置的密码)${NC}"
echo ""

if [ "$USE_WHITELIST" == "y" ]; then
    echo -e "${BLUE}访问限制：${NC}"
    echo -e "  ✓ HTTP 基本认证（用户名密码）"
    echo -e "  ✓ IP 白名单（仅以下 IP 可访问）"
    echo -e "$ALLOWED_IPS" | sed 's/allow //g' | sed 's/;//g' | sed 's/^/    /'
    echo ""
else
    echo -e "${BLUE}访问限制：${NC}"
    echo -e "  ✓ HTTP 基本认证（用户名密码）"
    echo -e "  ✗ IP 白名单未启用（任何 IP 可尝试登录）"
    echo ""
fi

echo -e "${YELLOW}⚠️  重要提示：${NC}"
echo -e "  1. 请配置防火墙开放端口："
echo -e "     ${BLUE}sudo ufw allow ${NGINX_PORT}/tcp${NC}"
echo ""
echo -e "  2. 修改 ${YELLOW}admin.html${NC} 中的 API 地址："
echo -e "     ${BLUE}const API_BASE = 'http://${SERVER_IP}:${NGINX_PORT}';${NC}"
echo -e "     ${BLUE}const WS_URL = 'ws://${SERVER_IP}:${NGINX_PORT}';${NC}"
echo ""
echo -e "配置文件备份："
echo -e "  ${NGINX_CONF}.backup.*"
echo ""
echo -e "修改密码："
echo -e "  ${BLUE}sudo htpasswd ${PASSWD_FILE} ${ADMIN_USER}${NC}"
echo ""
echo -e "添加新用户："
echo -e "  ${BLUE}sudo htpasswd ${PASSWD_FILE} newuser${NC}"
echo ""
